```{r fns}
corr_col <- function(x,
                     y = NULL,
                     ...,
                     x_name = "x",
                     y_name = "y",
                     xy_join_vars = NULL,
                     method = "spearman") {
  
  rlang::arg_match(method, c("pearson", "kendall", "spearman"))
  
  # Two cases: x, xy
  
  if (is.null(y)) {
    result <- corr_col_x(x = x,
                         x_name = x_name,
                         method = method) %>%
      dplyr::mutate(q = stats::p.adjust(p, method = "fdr"))
  } else {
    
    cli::cli_abort(c("Correlation with a second {.cls data.frame} has not been implemented yet!"))
    
    result <- corr_col_xy(
      x = x,
      y = y,
      xy_join_vars = xy_join_vars,
      x_name = x_name,
      y_name = y_name,
      method = method
    ) %>%
      dplyr::mutate(q = stats::p.adjust(p, method = "fdr")) %>%
      dplyr::group_by(x) %>%
      dplyr::mutate(q_x = stats::p.adjust(p, method = "fdr")) %>%
      dplyr::ungroup() %>%
      dplyr::group_by(y) %>%
      dplyr::mutate(q_y = stats::p.adjust(p, method = "fdr")) %>%
      dplyr::ungroup()
  }
  
  result %>%
    dplyr::rename_with(
      .fn = str_replace,
      .cols = contains("x"),
      pattern = "x$",
      replacement = x_name
    ) %>%
    dplyr::rename_with(
      .fn = str_replace,
      .cols = contains("y"),
      pattern = "y$",
      replacement = y_name
    ) %>%
    tibble::remove_rownames()
  
}

corr_col_x <- function(x, x_name, ..., method = "spearman") {
  require(magrittr)
  require(dplyr)
  require(purrr)
  
  rlang::arg_match(method, c("pearson", "kendall", "spearman"))
  arg_check_data(x, "x")
  
  corr_data <- x %>%
    select(where(is.numeric))
  
  if(ncol(corr_data) < 2) cli::cli_abort(c("{.var x} must have at least two numeric columns."))

  corr_vars <- corr_data %>%
    names() %>%
    combn(x = ., m = 2) %>%
    t() %>%
    tibble::as_tibble(.name_repair = "universal") %>%
    dplyr::rename(var_1 = ...1, var_2 = ...2)
  
  purrr::map2(.x = corr_vars$var_1,
             .y = corr_vars$var_2,
             .f = possibly(\(x, y) corr_x(x, y, corr_data, method))) %>%
    purrr::list_rbind()
  
}

corr_x <- function(x, y, corr_data, method) {
  rlang::arg_match(method, c("pearson", "kendall", "spearman"))
  
  tryCatch({
    cor_result <- cor.test(
      x = corr_data[[x]],
      y = corr_data[[y]],
      method = method,
      exact = FALSE
    )
    
    return(cbind(
      data.frame(x = x, y = y),
      statistic(cor_result$estimate, method),
      data.frame(p = cor_result$p.value,
                 error = NA)
    ))
    
  },
  warning = function(cond){
    return(cbind(
      data.frame(x = x, y = y),
      statistic(NA, method),
      data.frame(p = NA,
                 error = conditionMessage(cond))
    ))
  },
  error = function(cond){
    return(cbind(
      data.frame(x = x, y = y),
      statistic(NA, method),
      data.frame(p = NA,
                 error = conditionMessage(cond))
    ))
  })
}

statistic <- function(value, method) {
  rlang::arg_match(method, c("pearson", "kendall", "spearman"))
  
  switch (
    method,
    "pearson" = data.frame(cor = value),
    "kendall" = data.frame(tau = value),
    "spearman" = data.frame(rho = value)
  )
}

corr_col_xy <- function(x,
                        y,
                        ...,
                        xy_join_vars = NULL,
                        x_name = "x",
                        y_name = "y",
                        method = "spearman") {
  require(magrittr)
  require(dplyr)
  
  rlang::arg_match(method, c("pearson", "kendall", "spearman"))
  arg_check_data(x, "x")
  arg_check_data(y, "y")
}

pcor_col <- function(x,
                     y = NULL,
                     z = NULL,
                     ...,
                     x_name = "x",
                     y_name = "y",
                     z_name = "z",
                     xy_join_vars = NULL,
                     xz_join_vars = NULL,
                     method = "spearman") {
  # Two cases: x, xyz
  
}

pcor_col_x <- function(x,
                       x_name = "x",
                       ...,
                       method = "spearman") {
  rlang::arg_match(method, c("pearson", "kendall", "spearman"))
}


pcor_col_xyz <- function(x,
                         y,
                         z,
                         ...,
                         x_name = "x",
                         y_name = "y",
                         z_name = "z",
                         xy_join_vars = NULL,
                         xz_join_vars = NULL,
                         method = "spearman") {
  rlang::arg_match(method, c("pearson", "kendall", "spearman"))
  
}

arg_check_data <- function(arg_data, arg_name){
  
  require(magrittr)
  
  # Is it a data frame? ------------------------------------------
  
  if (!is.data.frame(arg_data)) cli::cli_abort(
    c("{.var {arg_name}} must be a {.cls data.frame}.",
      "x" = "You've supplied a {.cls {class(arg_data)}}"))
  
  # Does it contain numeric data? ------------------------------------------
  
  has_numeric_columns <- arg_data %>%
              dplyr::select(where(is.numeric)) %>%
              ncol() > 0
  
  if(!has_numeric_columns) cli::cli_abort(
    c("{.var {arg_data}} does not contain numeric columns.")
  )

}





```


```{r}
indexes <- c("a", "b", "c", "d", "e")
values_up <- c(1, 2, 3, 4, 5)
values_down <- c(5, 4, 3, 2, 1)
values_constant <- c(1, 1, 1, 1, 1)
values_up_na <- c(1, 2, 3, NA, 5)
values_dn_na <- c(5, NA, 3, 2, 1)
values_all_na <- as.numeric(c(NA, NA, NA, NA, NA))
values_single <- c(NA, NA, 3, NA, NA)
values_nonnumeric <- c("a", "b", "c", "d", "e")


```


```{r testing}

df1 <- data.frame(indexes,values_up)
arg_check_data(df1, "df1")
arg_check_data(1, "numeric input")
arg_check_data("1", "character input")
arg_check_data(c("1", 1), "list input")

arg_check_data(df1, "df1") 
df2 <- data.frame(indexes, values_nonnumeric)
arg_check_data(df2, "df2")
df3 <- data.frame(indexes, values_up, values_nonnumeric)
arg_check_data(df3, "df3")

# Does the error propagate up through function calls? Yes

corr_col_x(x = "1", x_name = "1")
corr_col_x(x = 1, x_name = "1")
corr_col_x(x = df1, x_name = "df1")
corr_col_x(x = df2, x_name = "df2")
corr_col_x(x = df3, x_name = "df3")

corr_col_xy(x = df1, y = df3)
corr_col_xy(x = df1, y = df2)
corr_col_xy(x = df1, y = "1")
corr_col_xy(x = 1, y = df1)

# What about method?
corr_col_xy(x = df1, y = df3, method = "garbage")
corr_col_xy(x = df1, y = df3, method = "kendall")
corr_col_xy(x = df1, y = df3, method = "k")


#

corr_col(x= data.frame(values_down, values_up, values_single, values_dn_na, values_up_na), y = data.frame(indexes), x_name = "test", y_name ="also")

```
